### ISSUE TITLE
UUID HOME error on Windows

### ISSUE THREAD

**Issue by timkoopmans** [timkoopmans/watirgrid#2]
When running a provider on windows you get the following error:

c:/ruby/lib/ruby/gems/1.8/gems/uuid-2.2.0/lib/uuid.rb:155:in `expand_path': coul
dn't find HOME environment -- expanding`~/.ruby-uuid' (ArgumentError) from c:/ruby/lib/ruby/gems/1.8/gems/uuid-2.2.0/lib/uuid.rb:155:in `state_file'
from c:/ruby/lib/ruby/gems/1.8/gems/uuid-2.2.0/lib/uuid.rb:187:in`initialize'
from c:/ruby/lib/ruby/gems/1.8/gems/watirgrid-0.0.6/lib/provider.rb:203:in `new'
from c:/ruby/lib/ruby/gems/1.8/gems/watirgrid-0.0.6/lib/provider.rb:203:in`start'
from c:/ruby/lib/ruby/gems/1.8/gems/watirgrid-0.0.6/bin/provider:63
from c:/ruby/bin/provider:19:in `load'
from c:/ruby/bin/provider:19

**Comment by timkoopmans** [comment]
This can be fixed by setting a HOME variable prior to running the provider
e.g.

set HOME=C:\

You can also set a permanent HOME variable in My Computer > Advanced tab > Environment variables
