### ISSUE TITLE
A nil object is returned for the DRb front object

### ISSUE THREAD

**Issue by timkoopmans** [timkoopmans/watirgrid#4]
Sometimes when instatiating a new GRID, a nil object is returned when calling the new_browser method of the browser[:object]

e.g.

```
I, [2011-04-06 15:45:30 #1172]  INFO -- : DRb server started on : druby://10.10.12.76:1336
I, [2011-04-06 15:45:30 #1172]  INFO -- : Controller found on   : druby://10.10.12.76:11235
I, [2011-04-06 15:45:30 #1172]  INFO -- : Found 1 tuples.
D, [2011-04-06T15:45:30.347000 #1172] DEBUG -- : Grid size   : 1
D, [2011-04-06T15:45:30.347000 #1172] DEBUG -- : Grid rampup   : 0.5 secs
D, [2011-04-06T15:45:30.847000 #1172] DEBUG -- : Browser 1#26479910 start  : Wed Apr 06 15:45:30 -0700 2011
D, [2011-04-06T15:45:30.847000 #1172] DEBUG -- : Browser 1#26479910 architecture  : i386-mswin32
D, [2011-04-06T15:45:30.847000 #1172] DEBUG -- : Browser 1#26479910 type  :
D, [2011-04-06T15:45:30.847000 #1172] DEBUG -- : Browser 1#26479910 hostname  : vm-qtpro2
(druby://10.10.12.163:11236) C:/utils/ruby/lib/ruby/gems/1.8/gems/watirgrid-1.0.3/lib/provider.rb:43:in `new_browser': undefined method `new' for nil:NilClass (NoMethodError)
from C:/utils/ruby/lib/ruby/gems/1.8/gems/watirgrid-1.0.3/lib/watirgrid.rb:77:in `join'
from C:/utils/ruby/lib/ruby/gems/1.8/gems/watirgrid-1.0.3/lib/watirgrid.rb:77:in `control'
from C:/utils/ruby/lib/ruby/gems/1.8/gems/watirgrid-1.0.3/lib/watirgrid.rb:77:in `each'
from C:/utils/ruby/lib/ruby/gems/1.8/gems/watirgrid-1.0.3/lib/watirgrid.rb:77:in `control'
from script.rb:24
```

**Comment by timkoopmans** [comment]
If you do not provide a -b flag to the provider startup, then a browser object is not created by the provider. -b flag for the provider has since been made mandatory.
